=== Ji-Hu/WebPrograming/second/tvschedule.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Banner" type="xs:string"/>
    <xs:element name="Date" type="xs:date"/>
    <xs:element name="Holiday" type="xs:string"/>
    <xs:element name="Time" type="xs:time"/>
    <xs:element name="Description" type="xs:string"/>

    <xs:attribute name="SName" type="xs:string"/>
    <xs:attribute name="CName" type="xs:string"/>
    <xs:attribute name="VTR" type="xs:string"/>
    <xs:attribute name="Rating" type="xs:string"/>
    <xs:attribute name="Language" type="xs:string"/>

    <xs:element name="ProgramSlot">
        <xs:complexType>
        <xs:sequence>
            <xs:element ref="Time"/>
            <xs:element name="Title">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="Rating"/>
                            <xs:attribute ref="Language"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element ref="Description" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute ref="VTR"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Day">
        <xs:complexType>
        <xs:sequence>
            <xs:element ref="Date"/>
            <xs:choice>
                <xs:element ref="Holiday"/>
                <xs:element ref="ProgramSlot" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Channel">
        <xs:complexType>
        <xs:sequence>
            <xs:element ref="Banner"/>
            <xs:element ref="Day" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="CName"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="TVSchedule">
        <xs:complexType>
        <xs:sequence>
        <xs:element ref="Channel" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="SName" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Ji-Hu/WebPrograming/second/tvsehedule.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<TVSchedule SName="LIFESHOW"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="tvschedule.xsd">

<Channel CName="1ch">
    <Banner>광고판1</Banner>
    <Day>
        <Date>2018-10-03</Date>
        <Holiday>개천절</Holiday>
    </Day>
</Channel>

<Channel CName="2ch">
    <Banner>banner</Banner>
    <Day>
        <Date>2018-09-13</Date>
        <ProgramSlot>
            <Time>12:00:00</Time>
            <Title>집에가자</Title>
        </ProgramSlot>
    </Day>
    <Day>
        <Date>2018-09-09</Date>
        <ProgramSlot>
            <Time>05:00:00</Time>
            <Title Rating="5.0" Language="Korean">Diver</Title>
        </ProgramSlot>
        <ProgramSlot VTR="on">
            <Time>19:00:00</Time>
            <Title>AquaMan</Title>
        </ProgramSlot>
    </Day>
</Channel>


</TVSchedule>
